//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLoginUser.WSLoginUsersSoap")]
    public interface WSLoginUsersSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginResponse login(Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginResponse> loginAsync(Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string nombre, string clave) {
            this.nombre = nombre;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSLoginUsersSoapChannel : Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.WSLoginUsersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSLoginUsersSoapClient : System.ServiceModel.ClientBase<Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.WSLoginUsersSoap>, Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.WSLoginUsersSoap {
        
        public WSLoginUsersSoapClient() {
        }
        
        public WSLoginUsersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSLoginUsersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLoginUsersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLoginUsersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginResponse Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.WSLoginUsersSoap.login(Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string nombre, string clave) {
            Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequest inValue = new Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequest();
            inValue.Body = new Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.clave = clave;
            Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginResponse retVal = ((Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.WSLoginUsersSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginResponse> Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.WSLoginUsersSoap.loginAsync(Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginResponse> loginAsync(string nombre, string clave) {
            Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequest inValue = new Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequest();
            inValue.Body = new Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.loginRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.clave = clave;
            return ((Proyecto_restaurant_Siglo_XXI.ServiceReferenceLoginUser.WSLoginUsersSoap)(this)).loginAsync(inValue);
        }
    }
}
